# spring.application.name=gestion-produits
spring.application.name=gestion-produits

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_produits
spring.datasource.username=gestion_user
spring.datasource.password=gestion_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080